title: 🔗 URL
baseline: URL manager & shortener
description: URL is an URL manager and shortener, powered by Cecil (a static site generator).
baseurl: https://url.cecil.app/
image: url-shortener.png
theme:
  - applanding
  - netlify
applanding:
  buttons:
    - name: Netlify
      url: https://app.netlify.com/start/deploy?repository=https://github.com/Cecilapp/url&stack=cms
      image: https://www.netlify.com/img/deploy/button.svg
  source: https://github.com/Cecilapp/url
  documentation: https://github.com/Cecilapp/url#readme
  screenshot:
    desktop: url-shortener.png
  demo: https://url-demo.cecil.app
netlify:
  redirects:
    - from: https://cecil-url.netlify.app/*
      to: https://url.cecil.app/:splat
      status: 301
      force: true
